Xth3unkn0wnx/offerings
acm-ucr/aiatucr-website pull request #15
Opened 2024-06-24 21:20 UTC by xTh3Unkn0wnx

![Screenshot 2024-06-24 141550](https://github.com/acm-ucr/aiatucr/assets/97139185/2c9dbb92-f31e-42af-8d1b-3cf3a7070bec)

- Created a component for Offering Cards
- Created a second component to render multiple Offering cards and hold the title for what's being offered.
- Added the OfferingCards component onto the landing page (page.js)

2024-06-25 01:08 UTC, khandrew1 requested changes
feel free to ask about any questions

2024-06-25 01:08 UTC, khandrew1 commented on src/app/page.js
> +    <>
Please remove `<>`

2024-06-25 01:08 UTC, khandrew1 commented on src/components/landing/OfferingCard.js
> +  }
If statements are unnecessary, as this is a static website, none of these props should be or ever will be blank

2024-06-25 01:08 UTC, khandrew1 commented on src/components/landing/OfferingCard.js
> +    <div className="h-80 w-72 rounded-3xl p-8 bg-[#AEC6D8] flex flex-col justify-between">
Don't use raw hex codes in the color, should be added as a custom color in the config

2024-06-25 01:08 UTC, khandrew1 commented on src/components/landing/OfferingCard.js
> +    <div className="h-80 w-72 rounded-3xl p-8 bg-[#AEC6D8] flex flex-col justify-between">
Also don't use specific values for the height, keep it at percentage values (fractions)

2024-06-25 01:08 UTC, khandrew1 commented on src/components/landing/OfferingCard.js
> +    <div className="h-80 w-72 rounded-3xl p-8 bg-[#AEC6D8] flex flex-col justify-between">
vh is fine too but only use when necessary

2024-06-25 01:08 UTC, khandrew1 commented on src/components/landing/OfferingCards.js
> +  null,
remove these nulls, i know the design was weird but may look better without them

2024-06-25 01:08 UTC, khandrew1 commented on src/components/landing/OfferingCards.js
> +        className="font-[Montserrat
again don't worry about the font

2024-06-25 01:08 UTC, khandrew1 commented on src/components/landing/OfferingCards.js
> +              title={offering?.title}
question marks aren't needed

2024-06-25 04:40 UTC, xTh3Unkn0wnx commented
![Screenshot 2024-06-24 212901](https://github.com/acm-ucr/aiatucr/assets/97139185/ee07cecc-6acf-4089-86ed-bd1c487bf5f3)

- Removed the react fragment (<>...</>) from the page.js
- Changed the height parameter for the card to a percentage
- Removed question marks when mapping the cards in OfferingCards.js
- Removed the font-[xxx] class, will worry about that later when we go over it
- Removed the nulls in the arrays of cards
- Changed the classes so it does not use [xxx] in the Classname
- Added two custom colors (The text gray and the blue for events bg and 404)
- Added the custom classes to OfferingCard.js so it can be used.
- Closed #6

2024-06-25 04:43 UTC, xTh3Unkn0wnx commented
If needed, I can use some random blue and gray color for the background and text color in their respective elements if we do not want to deal with tailwind configs just yet.

2024-06-28 02:23 UTC, khandrew1 requested changes

2024-06-28 02:23 UTC, khandrew1 commented on tailwind.config.js
>        ai: {},
put the colors in here, again like the other acm projects
example:
`ai : { "blue": "#AEC6D8" }`

2024-06-28 02:23 UTC, khandrew1 commented on tailwind.config.js
> +      },
remove this

2024-06-28 02:23 UTC, khandrew1 commented on src/components/landing/OfferingCards.js
> +    icon: <LiaNewspaperSolid className="size-12 text-[#4F9AD7]" />,
don't use size for the icons, use font sizes like `text-xl` or whatever fits

2024-06-28 02:23 UTC, khandrew1 commented on src/components/landing/OfferingCards.js
> +    icon: <LiaNewspaperSolid className="size-12 text-[#4F9AD7]" />,
also color, don't use raw hex codes.

2024-06-28 02:23 UTC, khandrew1 commented on src/components/landing/OfferingCard.js
> +    <div className="h-full w-72 rounded-3xl p-8 bg-ai-event-blue flex flex-col justify-between">
widths should also not use pixel values

2024-06-28 02:23 UTC, khandrew1 commented on src/components/landing/OfferingCards.js
> +const OfferingCards = ({}) => {
remove empty object, if there are no props parameters should stay empty, `()`

2024-06-28 02:23 UTC, khandrew1 commented on src/components/landing/OfferingCards.js
> +      <h2 className="text-4xl text-[#4F9AD7] text-center m-8">We Offer...</h2>
do not use `<h2>` tags (it can mess with SEO)
instead use `<p>` tags with font sizes given in the tailwind docs

2024-06-28 04:39 UTC, xTh3Unkn0wnx commented
![Screenshot 2024-06-27 213043](https://github.com/acm-ucr/aiatucr-website/assets/97139185/67b63a40-ae01-4aff-a389-e01ad318a85d)

- Changed the tailwind config to match the desired format and scheme mentioned by lead
- changed width to use fractional/percentage units instead
- removed an empty object for the OfferingCards component 
- Changed an element from h2 to p 
- Used text-5xl for icons rather than size-x
- Closed #6

2024-07-06 18:08 UTC, merged