Implement Navigation
acm-ucr/aiatucr-website pull request #16
Opened 2024-06-25 01:28 UTC by jisubang1001

- Added Navigation
- Closes #7

2024-06-25 05:57 UTC, jisubang1001 commented
I accidentally left my previous version of code on the bottom of NavBar. Please just ignore them.

2024-06-28 02:30 UTC, khandrew1 requested changes

2024-06-28 02:30 UTC, khandrew1 commented on tailwind.config.js
>        ai: {},
colors are supposed to be in this object

2024-06-28 02:30 UTC, khandrew1 commented on src/components/NavBar.jsx
> +*/
remove all this comments, you can always just make new commits before submitting PRs for review

2024-06-28 02:30 UTC, khandrew1 commented on src/components/NavBar.jsx
> +import React, { useState } from "react";
do not import React

2024-06-28 02:30 UTC, khandrew1 commented on src/components/NavBar.jsx
> +import logo from "@/public/logo.png";
do not import images like this, when they are in public they can be referenced such as `/logo.png`
for more information: https://nextjs.org/docs/app/building-your-application/optimizing/static-assets

2024-07-07 18:44 UTC, merged