Implement Project Card
acm-ucr/aiatucr-website pull request #30
Opened 2024-07-05 19:05 UTC by houstongunter

- Added two project card components
- One component has the text left of the image
- Other component has the text right of the image
- Closes #10 
![Image 7-5-24 at 12 02 PM](https://github.com/acm-ucr/aiatucr-website/assets/147109020/0f52d74a-44e3-45bf-8b7f-e9ccfb2ff044)

2024-07-07 19:03 UTC, khandrew1 commented
Component files should be using `.jsx` file extension, also should be in the folder `components/projects`

2024-07-22 17:20 UTC, khandrew1 requested changes

2024-07-22 17:20 UTC, khandrew1 commented on src/components/landing/ProjectCardLeft.js
> +      {/* Text below the image on small screens */}
remove all comments

2024-07-22 17:20 UTC, khandrew1 commented on src/components/landing/ProjectCardLeft.js
> +            style={{ fontSize: "clamp(1rem, 5vw, 2rem)" }}
no normal css, you shouldnt even need to do something this complicated?

2024-07-22 17:20 UTC, khandrew1 commented on src/components/landing/ProjectCardRight.js
> +            style={{ fontSize: "clamp(1rem, 5vw, 2rem)" }}
no normal css again

2024-07-22 17:20 UTC, khandrew1 commented on src/components/landing/ProjectCardRight.js
> +          className="w-full h-auto"
sorry for being confusing on this in the beginning, please import `projectCard.webp` on top like
`import projectCard from "@/public/projectCard.webp"` and then use that as the source and remove width and height

2024-07-22 17:20 UTC, khandrew1 commented on src/components/landing/ProjectCardLeft.js
> +        />
sorry for being confusing on this in the beginning, please import `projectCard.webp` on top like
`import projectCard from "@/public/projectCard.webp"` and then use that as the source and remove width and height

2024-07-22 17:20 UTC, khandrew1 commented on src/app/page.js
> +import React from "react";
remove react imports from every file

2024-07-22 17:20 UTC, khandrew1 commented on src/app/page.js
>  const Home = () => {
change this back to only offering cards, put these project cards on /projects

2024-07-22 17:20 UTC, khandrew1 commented on src/app/projects/page.js
>    return <>Projects</>;
put project card components on this page

2024-07-22 17:20 UTC, khandrew1 commented on src/components/projects/ProjectCardLeft.jsx
> +          height={436.31}
import image statically on top, `import projectCard from @/public/projectCard.webp` then use that as the src, `src={projectCard}` and remove static heights and width

2024-07-30 07:18 UTC, houstongunter commented
I don't know why one of the tests failed and I don't know why it's saying I added the offering cards files and changed the location of information.jsx I swear I didn't touch those

2024-07-31 07:35 UTC, khandrew1 commented
don't worry smth messed up within the directories

2024-07-31 07:36 UTC, khandrew1 requested changes

2024-07-31 07:36 UTC, khandrew1 commented on src/components/projects/OfferingCards.js
> +];
move this to a data file

2024-07-31 07:36 UTC, khandrew1 commented on src/components/projects/OfferingCards.js
> +];
also lowercase variables for data vars

2024-08-02 16:47 UTC, khandrew1 approved these changes

2024-08-04 22:56 UTC, merged